; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[platformio]
description = Arduino code to control mascot features (liquid pump, cheeks leds etc...)
default_envs = ArduinoNano

[env:ArduinoNano]
platform = atmelavr
board = nanoatmega328new
framework = arduino
upload_port = /dev/ttyUSB0
build_flags = -std=c++1z
test_framework = unity
lib_deps = dfrobot/DFRobotDFPlayerMini@^1.0.6

[env:native]
platform = native
build_flags = -std=c++1z
	-DunitTesting
	-lgcov
	--coverage
	-fprofile-abs-path
test_framework = unity
lib_deps = dfrobot/DFRobotDFPlayerMini@^1.0.6
